# -*- coding: utf-8 -*-
"""to_csv_from_excel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rsLMn_os8DSCuB2PkitQOTE3Ad8qaXOB
"""

# Convert Online Retail Excel to CSV for PySpark ingestion.
import pandas as pd
from pathlib import Path

infile = Path("/content/sample_data/data_raw/Online_Retail.xlsx")
outfile = Path("data_raw/online_retail.csv")

# Create data_raw directory if it doesn't exist for the output file
outfile.parent.mkdir(parents=True, exist_ok=True)

if not infile.exists():
    raise FileNotFoundError(f"{infile} not found. Put the Excel file in /content/sample_data/data_raw/")

df = pd.read_excel(infile)
# basic cleanup
df.dropna(subset=["InvoiceNo", "StockCode"], inplace=True)
# ensure InvoiceDate is datetime
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
# write to CSV
df.to_csv(outfile, index=False)
print(f"Wrote {outfile} ({len(df)} rows)")

import os
if os.path.exists('data_raw'):
    print(os.listdir('data_raw'))
else:
    print('The directory data_raw does not exist.')

