# -*- coding: utf-8 -*-
"""basket_rules.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OEQh0opTTIFH9gw5fhYgU4vdbhg2ES2N
"""

"""Produce frequent itemsets and association rules for Market Basket Analysis."""
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules
from pathlib import Path

infile = Path('/content/drive/MyDrive/Navttc Project/data/online_retail_scaled.csv')  # or read Parquet via pyarrow
out_rules = Path('/content/drive/MyDrive/Navttc Project/reports/basket_rules.csv')

if not infile.exists():
    raise FileNotFoundError('Place CSV in data/ or run scale_simulation first')

df = pd.read_csv(infile, parse_dates=['InvoiceDate'])
# For example, filter Germany
df = df[df['Country'] == 'Germany']

# Create basket: pivot transactions x items
basket = (
    df.groupby(['InvoiceNo', 'Description'])['Quantity']
    .sum().unstack().fillna(0)
)
# encode
basket = basket.applymap(lambda x: 1 if x > 0 else 0)

freq = apriori(basket, min_support=0.01, use_colnames=True)
rules = association_rules(freq, metric='lift', min_threshold=1.0)

rules.to_csv(out_rules, index=False)
print(f"Saved rules to {out_rules}")