# -*- coding: utf-8 -*-
"""create_sqlite_dims.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bZncx6RhhmBX9cD0f821CLoN7munN2HP
"""

"""Create dimension tables (product, customer) and save to sqlite for small joins."""
import sqlite3
import pandas as pd
from pathlib import Path

conn = sqlite3.connect('sqlite/retail_dims.db')
Path('sqlite').mkdir(exist_ok=True)

# Example: product dim from raw CSV
df = pd.read_csv('data_raw/online_retail.csv')
prod = df[['StockCode', 'Description']].drop_duplicates().reset_index(drop=True)
prod.to_sql('product_dim', conn, if_exists='replace', index=False)

cust = df[['CustomerID']].drop_duplicates().reset_index(drop=True)
cust.to_sql('customer_dim', conn, if_exists='replace', index=False)

conn.close()
print('Wrote sqlite/retail_dims.db')