# -*- coding: utf-8 -*-
"""scale_simulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/115Bug3-jezT0kQzX53xv3HoAwMaNMCId
"""

#"""Create a larger dataset by duplicating and shifting invoice dates to simulate months of data."""
import pandas as pd
from pathlib import Path

# Changed the source path to use the existing file in /content/
src = Path("/content/Online_Retail.csv")
out = Path("data/online_retail_scaled.csv")

if not src.exists():
    # This check will now verify if /content/Online_Retail.csv exists
    raise FileNotFoundError(f"Source file not found at {src}. Please ensure it exists.")

# Create the output directory if it doesn't exist
out.parent.mkdir(parents=True, exist_ok=True)

df = pd.read_csv(src, parse_dates=["InvoiceDate"])

# replicate N times shifting InvoiceDate by months
N = 10
frames = []
for i in range(N):
    tmp = df.copy()
    tmp["InvoiceNo"] = tmp["InvoiceNo"].astype(str) + f"-S{i}"
    tmp["InvoiceDate"] = tmp["InvoiceDate"] + pd.DateOffset(months=i)
    frames.append(tmp)

big = pd.concat(frames, ignore_index=True)
big.to_csv(out, index=False)
print(f"Wrote scaled CSV with {len(big)} rows -> {out}")